title: ELSM
author: Naila Hamid, Nazar Khan and Arbish Akram
description: Computer Vision & Machine Learning Group, Department of Computer Science, University of the Punjab, Lahore, Pakistan
theme: jekyll-theme-minimal
